name: Build Native Image
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          native-image-job-reports: 'true'
      - name: Grant execute permission for Gradle wrapper (Linux only)
        if: runner.os == 'Linux'
        run: chmod +x gradlew
      - name: Build for Linux
        if: runner.os == 'Linux'
        run: ./linux/build.sh
      - name: Upload Native Binary (Linux only)
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: cowsay-linux
          path: ./cowsay  
